repos:
	- repo: local
		hooks:
			- id: run-tests
				name: Run repository tests
				entry: make test
				language: system
				always_run: true

	- repo: https://github.com/pre-commit/pre-commit-hooks
		rev: v4.4.0
		hooks:
			- id: trailing-whitespace
			- id: end-of-file-fixer
			- id: check-yaml

	- repo: https://github.com/pre-commit/mirrors-shellcheck
		rev: v0.8.0
		hooks:
			- id: shellcheck

	- repo: https://github.com/codespell-project/codespell
		rev: v2.2.0
		hooks:
			- id: codespell
